package main

import (
	"log"

	_ "github.com/ariyaagustian/gin-boilerplate/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"

	"github.com/ariyaagustian/gin-boilerplate/internal/config"
	"github.com/ariyaagustian/gin-boilerplate/internal/db"
	"github.com/ariyaagustian/gin-boilerplate/internal/domain"
	"github.com/ariyaagustian/gin-boilerplate/internal/repository"
	"github.com/ariyaagustian/gin-boilerplate/internal/service"
	transport "github.com/ariyaagustian/gin-boilerplate/internal/transport/http"
	"github.com/ariyaagustian/gin-boilerplate/internal/transport/http/handler"
)

// @title Gin CRUD Boilerplate API
// @version 1.0
// @description This is a sample CRUD API boilerplate with Gin and GORM
// @termsOfService http://swagger.io/terms/

// @contact.ariyaagustian API Support
// @contact.url http://www.swagger.io/support
// @contact.ariyaagustian@gmail.com support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8081
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// load config & db
	cfg := config.Load()
	var gdb *gorm.DB = db.Open(cfg.DSN)
	if err := gdb.AutoMigrate(&domain.User{}); err != nil {
		log.Fatal("auto migrate:", err)
	}

	// wiring dependency
	v := validator.New()
	userRepo := repository.NewUserRepository(gdb)

	userSvc := service.NewUserSvc(userRepo, v)
	authSvc := service.NewAuthSvc(userRepo, v, cfg.JWTSecret, cfg.JWTAccessTTL)

	userH := handler.NewUserHandler(userSvc)
	authH := handler.NewAuthHandler(authSvc)

	// router (public + protected)
	r := transport.NewRouter(userH, authH, cfg.JWTSecret, gdb)

	log.Printf("listening at :%s", cfg.AppPort)
	if err := r.Run(":" + cfg.AppPort); err != nil {
		log.Fatal(err)
	}
}
